### ISSUE TITLE
Hint

### ISSUE THREAD

**Issue by char1129** [char1129/registration-form#1]
@muxlowc @mackenzierose

Good afternoon/break Ladies,

My brain is fried from working on assignments all break so far. I have to ask. Are we using grids to resize this form? Or is it a case of inline-block + padding + center?

Thank you!

**Comment by muxlowc** [comment]
@char1129 

You will only have a grid surrounding the part that has name/age/email/fitness, and there's no inline-block. Also make sure you add a max-length to the whole form ;)

Hope this helps!

**Comment by char1129** [comment]
@muxlowc  
I'll try the max-length. I had thought about adding it but seems like I never got around to it in the code. Silly me. 
In regards to the inline-block. I was wondering how they got side by side like in resolutions 960 and 1440? I watched Thomas's videos and he only shows the reverse (how to move them to new rows).  I never had the issue with them sitting on the same line. Let me tinker with it a bit - if I don't figure it out I'll comment on here again later.

Thank you!
Have a great evening! 😊

**Comment by muxlowc** [comment]
@char1129  If you think that those 4 fields are actually only taking up 50%  of the width on large/100% on small – does that help?

**Comment by char1129** [comment]
> @char1129 If you think that those 4 fields are actually only taking up 50% of the width on large/100% on small – does that help?

Oh ff- yes. Thank you. 🙏  @muxlowc

![idiotsandwich](https://user-images.githubusercontent.com/55107755/75415182-d2345480-58f8-11ea-8e8f-5a04872a22d3.png)
